#include<bits/stdc++.h>
using namespace std;
int Sum(int A , int B){
    return A+B;
}
int main(){ 
   int a , b;
    cout<<"Enter a , b ";
    cin >>a>>b;
    cout << a <<" + " <<b <<" = "<<Sum(a,b) << endl ;
    cout<<"Enter a , b ";
    cin >>a>>b;
    cout << a <<" + " <<b <<" = "<<Sum(a,b) << endl ;
    cout<<"Enter a , b ";
    cin >>a>>b;
    cout << a <<" + " <<b <<" = "<<Sum(a,b) << endl ;
    return 0;
}